### ISSUE TITLE
Cannot read property 'absWorkingDir' of undefined

### ISSUE THREAD

**Issue by nelsliu9121** [ArtiomTr/aqu#42]
Build error when *aqu* is used with [@vanilla-extract/esbuild-plugin](https://www.npmjs.com/package/@vanilla-extract/esbuild-plugin)

I digged around for a bit and I think [this line](https://github.com/seek-oss/vanilla-extract/blob/35af8d18c437852f35961d400d74abdad208f0e0/packages/esbuild-plugin/src/index.ts#L60) is where it went wrong.
But when I use the same plugin for _esbuild_-only project, it worked just fine.
So I'm guessing the `build.initialOptions` is not properly passed down?

Here's a [reproducible repo](https://github.com/nelsliu9121/aqu-vanilla-extract-reproduce-repo).

**Comment by ArtiomTr** [comment]
Hi @nelsliu9121,

Thanks for reporting the bug! I will try to fix this problem as soon as possible.

**Comment by ArtiomTr** [comment]
The problem came from an old version of esbuild - [as stated in the esbuild documentation](https://esbuild.github.io/plugins/), the plugin API is still experimental. I have updated esbuild version to the latest in #43. This PR solves the issue, but not completely. The bug with `absWorkingDir` has been fixed, but now esbuild versions conflict - `vanilla-extract` uses version `0.11.16`, but `aqu` uses version `0.12.16` (latest at this moment). If you'd like to use `vanilla-extract` with `aqu`, please ask the `vanilla-extract` maintainers to update `esbuild` in their dependencies.

**Comment by ArtiomTr** [comment]
If you'll face any other issue, feel free to ask for help, I will try to help as much as I can!
